import { Parser } from 'htmlparser2';


export interface ParsedNode {
  tagName: string;
  id: string;
  classes: string[];
  startLine: number;
  startCol: number;
  endLine: number;
  endCol: number;
  parent: ParsedNode | null;
  children: ParsedNode[];
  nthOfType: number; // 1-based index among siblings of same tag
}

export class HtmlParser {
  /**
   * Given an HTML string and cursor position (0-indexed line/col),
   * returns the most specific ParsedNode at that position.
   */
  findNodeAtPosition(html: string, line: number, col: number): ParsedNode | null {
    const nodes = this.buildTree(html);
    return this.searchTree(nodes, line, col);
  }

  /**
   * Given an HTML string and a CSS selector generated by generateSelector() or
   * highlight.js buildSelector(), walks the parsed tree and returns the matching node.
   * Returns null if no match is found.
   *
   * Supports two formats:
   *  - Full path: 'html:nth-of-type(1) > body:nth-of-type(1) > div:nth-of-type(2)'
   *  - Partial path: 'body:nth-of-type(1) > div:nth-of-type(2)' (starts below html)
   */
  findNodeBySelector(html: string, selector: string): ParsedNode | null {
    const nodes = this.buildTree(html);
    const steps = selector.split('>').map((s) => s.trim()).filter(Boolean);
    if (steps.length === 0) { return null; }

    // Try full path first (starts at root)
    const direct = this.walkBySteps(nodes, steps, 0);
    if (direct) { return direct; }

    // Fallback: try starting from each node in the tree (handles partial selectors)
    return this.deepSearch(nodes, steps);
  }

  /**
   * Generates a unique CSS selector path for a node, e.g.:
   *   body > div:nth-of-type(2) > p:nth-of-type(1)
   */
  generateSelector(node: ParsedNode): string {
    const parts: string[] = [];
    let current: ParsedNode | null = node;
    while (current) {
      let part = current.tagName;
      if (current.id) {
        part += `#${current.id}`;
      } else {
        part += `:nth-of-type(${current.nthOfType})`;
      }
      parts.unshift(part);
      current = current.parent;
    }
    return parts.join(' > ');
  }

  // ── Private ──────────────────────────────────────────────────────────────────

  private buildTree(html: string): ParsedNode[] {
    const lines = html.split('\n');

    /**
     * Maps a character offset in the full HTML string to {line, col} (0-indexed).
     */
    const offsetToLineCol = (() => {
      // Pre-compute cumulative offsets per line for O(1) lookup
      const offsets: number[] = [];
      let total = 0;
      for (const ln of lines) {
        offsets.push(total);
        total += ln.length + 1; // +1 for \n
      }
      return (offset: number): { line: number; col: number } => {
        let lo = 0;
        let hi = offsets.length - 1;
        while (lo < hi) {
          const mid = Math.floor((lo + hi + 1) / 2);
          if (offsets[mid] <= offset) {
            lo = mid;
          } else {
            hi = mid - 1;
          }
        }
        return { line: lo, col: offset - offsets[lo] };
      };
    })();

    const roots: ParsedNode[] = [];
    const stack: ParsedNode[] = [];

    const parser = new Parser(
      {
        onopentag(name, attrs) {
          const offset = parser.startIndex;
          const { line, col } = offsetToLineCol(offset);

          // Count nth-of-type among siblings
          const siblings = stack.length > 0 ? stack[stack.length - 1].children : roots;
          const nthOfType = siblings.filter((s) => s.tagName === name).length + 1;

          const node: ParsedNode = {
            tagName: name,
            id: (attrs['id'] as string) || '',
            classes: ((attrs['class'] as string) || '').split(/\s+/).filter(Boolean),
            startLine: line,
            startCol: col,
            endLine: line,
            endCol: col,
            parent: stack.length > 0 ? stack[stack.length - 1] : null,
            children: [],
            nthOfType,
          };

          if (stack.length > 0) {
            stack[stack.length - 1].children.push(node);
          } else {
            roots.push(node);
          }
          stack.push(node);
        },

        onclosetag(_name) {
          const node = stack.pop();
          if (node) {
            const { line, col } = offsetToLineCol(parser.endIndex + 1);
            node.endLine = line;
            node.endCol = col;
          }
        },
      },
      { lowerCaseTags: true, lowerCaseAttributeNames: true }
    );

    parser.write(html);
    parser.end();

    return roots;
  }

  /** Depth-first search: returns the deepest node that contains (line, col) */
  private searchTree(nodes: ParsedNode[], line: number, col: number): ParsedNode | null {
    let best: ParsedNode | null = null;

    for (const node of nodes) {
      if (this.contains(node, line, col)) {
        best = node;
        const childMatch = this.searchTree(node.children, line, col);
        if (childMatch) {
          best = childMatch;
        }
      }
    }

    return best;
  }

  /** Recursively match selector steps against the tree */
  private walkBySteps(nodes: ParsedNode[], steps: string[], depth: number): ParsedNode | null {
    if (depth >= steps.length) { return null; }
    const step = steps[depth];
    const { tag, id, nth } = this.parseStep(step);

    for (const node of nodes) {
      if (node.tagName !== tag) { continue; }
      // Match by id (takes priority, stops climbing)
      if (id && node.id !== id) { continue; }
      // Match by nth-of-type when no id
      if (!id && nth !== undefined && node.nthOfType !== nth) { continue; }

      // Last step → this is the target
      if (depth === steps.length - 1) { return node; }

      // Recurse into children for next step
      const child = this.walkBySteps(node.children, steps, depth + 1);
      if (child) { return child; }
    }
    return null;
  }

  /**
   * Fallback: try each node as the root of the selector (handles partial selectors
   * that don't start at the html root, e.g. 'body > div:nth-of-type(1)')
   */
  private deepSearch(nodes: ParsedNode[], steps: string[]): ParsedNode | null {
    for (const node of nodes) {
      // Try this node as step[0]
      const result = this.walkBySteps([node], steps, 0);
      if (result) { return result; }
      // Recurse into its children
      const childResult = this.deepSearch(node.children, steps);
      if (childResult) { return childResult; }
    }
    return null;
  }


  /** Parses a single selector step like 'div:nth-of-type(3)' or 'span#main-id' */
  private parseStep(step: string): { tag: string; id: string | null; nth: number | undefined } {
    // ID selector: tag#id
    const idMatch = step.match(/^([a-z0-9-]+)#([^:]+)$/i);
    if (idMatch) {
      return { tag: idMatch[1].toLowerCase(), id: idMatch[2], nth: undefined };
    }
    // nth-of-type selector: tag:nth-of-type(n)
    const nthMatch = step.match(/^([a-z0-9-]+):nth-of-type\((\d+)\)$/i);
    if (nthMatch) {
      return { tag: nthMatch[1].toLowerCase(), id: null, nth: parseInt(nthMatch[2], 10) };
    }
    // Plain tag
    return { tag: step.toLowerCase(), id: null, nth: undefined };
  }

  private contains(node: ParsedNode, line: number, col: number): boolean {
    if (line < node.startLine || line > node.endLine) {
      return false;
    }
    if (line === node.startLine && col < node.startCol) {
      return false;
    }
    if (line === node.endLine && col > node.endCol) {
      return false;
    }
    return true;
  }
}
